# FROM alpine:3.9.3
# LABEL maintainer="Collabnix"

# WORKDIR /opt/folder1
# RUN echo "Welcome to Docker Labs" > opt.txt
# WORKDIR /var/tmp


FROM alpine:3.9.3
LABEL maintainer="Collabnix"

ENV DIRPATH /myfolder
WORKDIR $DIRPATH